image_root: 'coco'
ann_root: 'annotation'
coco_gt_root: 'annotation/coco_gt'
# set pretrained as a file path or an url
pretrained: output/Pretrain7/checkpoint_29.pth
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/#model_base_capfilt_large.pth'
#pretrained: model/model_large_caption.pth

# size of vit model; base or large3
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 1
init_lr: 1e-5

#vit: 'large'
#vit_grad_ckpt: True
#vit_ckpt_layer: 5
#batch_size: 16
#init_lr: 2e-6

image_size: 384

# generation configs
max_length: 40
min_length: 10
num_beams: 5
prompt: 'a picture of'

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

